// Servicio de detección: Detector de IA y Detector de Plagio
// detectAI usa Gemini para analizar patrones de escritura artificial
// detectPlagiarism usa Google Custom Search para buscar fragmentos del texto en internet

const { GoogleGenerativeAI } = require("@google/generative-ai");
const axios = require("axios");

// ─── DETECTOR DE IA ───────────────────────────────────────────────────────────

async function detectAI(text) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY no configurada en .env");

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

  // Tomamos una muestra representativa (primeros 4000 chars) para el análisis
  const sample = text.substring(0, 4000);

  const prompt = `You are an expert AI content detector. Analyze the following text and determine the probability that it was generated by an AI (like ChatGPT, Gemini, Claude, etc.).

Analyze these specific indicators:
1. Repetitive sentence structures
2. Overly formal or uniform transitions ("Furthermore", "Moreover", "In conclusion")
3. Lack of personal voice, opinions, or emotion
4. Generic and predictable phrases
5. Perfect grammatical consistency without natural errors
6. Absence of anecdotes or concrete specific details
7. Balanced structure that is too "perfect"

IMPORTANT: You MUST respond ONLY with a valid JSON object, no markdown, no explanation — just the JSON.

Response format:
{
  "score": <number from 0 to 100 representing % probability of AI generation>,
  "verdict": "<one of: 'Humano', 'Posiblemente Humano', 'Incierto', 'Posiblemente IA', 'Generado por IA'>",
  "details": "<2-3 sentence explanation in Spanish of the key indicators found>"
}

Text to analyze:
${sample}`;

  const result = await model.generateContent(prompt);
  const responseText = result.response.text().trim();

  // Extraemos el JSON de la respuesta
  const jsonMatch = responseText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("El modelo no devolvió un JSON válido");

  return JSON.parse(jsonMatch[0]);
}

// ─── DETECTOR DE PLAGIO ───────────────────────────────────────────────────────

async function detectPlagiarism(text) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY no configurada en .env");

  const genAI = new GoogleGenerativeAI(apiKey);
  // Usamos gemini-2.0-flash con base de datos amplia para reconocer fuentes
  const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

  const sample = text.substring(0, 4000);

  const prompt = `Act as an expert plagiarism checker. Analyze the following text and determine if it contains copied content from known internet sources, articles, books, or websites based on your training data.

IMPORTANT: You MUST respond ONLY with a valid JSON object, no markdown, no explanation — just the JSON.

Response format:
{
  "score": <number from 0 to 100 representing % probability of plagiarism>,
  "verdict": "<one of: 'Sin Plagio', 'Plagio Mínimo', 'Posible Plagio', 'Plagio Moderado', 'Alto Plagio', 'Plagio Severo'>",
  "details": "<2-3 sentence explanation in Spanish of what you found>",
  "matches": [
    {
      "fragment": "<short quote from the text that seems copied>",
      "sources": [
        { "title": "<name of the source, author, or article>", "link": "<domain or book name>" }
      ]
    }
  ]
}
If no plagiarism is detected, return score 0, verdict 'Sin Plagio', and an empty array for matches.

Text to analyze:
${sample}`;

  const result = await model.generateContent(prompt);
  const responseText = result.response.text().trim();

  const jsonMatch = responseText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("El modelo no devolvió un JSON válido");

  return JSON.parse(jsonMatch[0]);
}

module.exports = { detectAI, detectPlagiarism };
